#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoSecondLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Rsi_ADX")]
	public partial class RSI_ADX_SIMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblSetting(tblSetting instance);
    partial void UpdatetblSetting(tblSetting instance);
    partial void DeletetblSetting(tblSetting instance);
    partial void Inserttbl5Minute(tbl5Minute instance);
    partial void Updatetbl5Minute(tbl5Minute instance);
    partial void Deletetbl5Minute(tbl5Minute instance);
    #endregion
		
		public RSI_ADX_SIMDataContext() : 
				base(global::AlgoSecondLayer.Properties.Settings.Default.Rsi_ADXConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RSI_ADX_SIMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RSI_ADX_SIMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RSI_ADX_SIMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RSI_ADX_SIMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblSetting> tblSettings
		{
			get
			{
				return this.GetTable<tblSetting>();
			}
		}
		
		public System.Data.Linq.Table<tbl5Minute> tbl5Minutes
		{
			get
			{
				return this.GetTable<tbl5Minute>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSettings")]
	public partial class tblSetting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private System.Nullable<int> _ADX_START;
		
		private System.Nullable<int> _ADX_END;
		
		private System.Nullable<int> _ADX_CURRENT;
		
		private System.Nullable<int> _RSI_START;
		
		private System.Nullable<int> _RSI_END;
		
		private System.Nullable<int> _RSI_CURRENT;
		
		private System.Nullable<double> _MAMA_1_START;
		
		private System.Nullable<double> _MAMA_1_END;
		
		private System.Nullable<double> _MAMA_1_CURRENT;
		
		private System.Nullable<double> _MAMA_2_START;
		
		private System.Nullable<double> _MAMA_2_END;
		
		private System.Nullable<double> _MAMA_2_CURRENT;
		
		private System.Nullable<int> _RSI_EMA_START;
		
		private System.Nullable<int> _RSI_EMA_END;
		
		private System.Nullable<int> _RSI_EMA_CURRENT;
		
		private System.Nullable<int> _RSI_SLOPE_START;
		
		private System.Nullable<int> _RSI_SLOPE_END;
		
		private System.Nullable<int> _RSI_SLOPE_CURRENT;
		
		private System.Nullable<int> _RSI_TOP_START;
		
		private System.Nullable<int> _RSI_TOP_END;
		
		private System.Nullable<int> _RSI_TOP_CURRENT;
		
		private System.Nullable<int> _RSI_BOTTOM_START;
		
		private System.Nullable<int> _RSI_BOTTOM_END;
		
		private System.Nullable<int> _RSI_BOTTOM_CURRENT;
		
		private System.Nullable<int> _DMI_PLUS_START;
		
		private System.Nullable<int> _DMI_PLUS_END;
		
		private System.Nullable<int> _DMI_PLUS_CURRENT;
		
		private System.Nullable<int> _DMI_MINUS_START;
		
		private System.Nullable<int> _DMI_MINUS_END;
		
		private System.Nullable<int> _DMI_MINUS_CURRENT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnADX_STARTChanging(System.Nullable<int> value);
    partial void OnADX_STARTChanged();
    partial void OnADX_ENDChanging(System.Nullable<int> value);
    partial void OnADX_ENDChanged();
    partial void OnADX_CURRENTChanging(System.Nullable<int> value);
    partial void OnADX_CURRENTChanged();
    partial void OnRSI_STARTChanging(System.Nullable<int> value);
    partial void OnRSI_STARTChanged();
    partial void OnRSI_ENDChanging(System.Nullable<int> value);
    partial void OnRSI_ENDChanged();
    partial void OnRSI_CURRENTChanging(System.Nullable<int> value);
    partial void OnRSI_CURRENTChanged();
    partial void OnMAMA_1_STARTChanging(System.Nullable<double> value);
    partial void OnMAMA_1_STARTChanged();
    partial void OnMAMA_1_ENDChanging(System.Nullable<double> value);
    partial void OnMAMA_1_ENDChanged();
    partial void OnMAMA_1_CURRENTChanging(System.Nullable<double> value);
    partial void OnMAMA_1_CURRENTChanged();
    partial void OnMAMA_2_STARTChanging(System.Nullable<double> value);
    partial void OnMAMA_2_STARTChanged();
    partial void OnMAMA_2_ENDChanging(System.Nullable<double> value);
    partial void OnMAMA_2_ENDChanged();
    partial void OnMAMA_2_CURRENTChanging(System.Nullable<double> value);
    partial void OnMAMA_2_CURRENTChanged();
    partial void OnRSI_EMA_STARTChanging(System.Nullable<int> value);
    partial void OnRSI_EMA_STARTChanged();
    partial void OnRSI_EMA_ENDChanging(System.Nullable<int> value);
    partial void OnRSI_EMA_ENDChanged();
    partial void OnRSI_EMA_CURRENTChanging(System.Nullable<int> value);
    partial void OnRSI_EMA_CURRENTChanged();
    partial void OnRSI_SLOPE_STARTChanging(System.Nullable<int> value);
    partial void OnRSI_SLOPE_STARTChanged();
    partial void OnRSI_SLOPE_ENDChanging(System.Nullable<int> value);
    partial void OnRSI_SLOPE_ENDChanged();
    partial void OnRSI_SLOPE_CURRENTChanging(System.Nullable<int> value);
    partial void OnRSI_SLOPE_CURRENTChanged();
    partial void OnRSI_TOP_STARTChanging(System.Nullable<int> value);
    partial void OnRSI_TOP_STARTChanged();
    partial void OnRSI_TOP_ENDChanging(System.Nullable<int> value);
    partial void OnRSI_TOP_ENDChanged();
    partial void OnRSI_TOP_CURRENTChanging(System.Nullable<int> value);
    partial void OnRSI_TOP_CURRENTChanged();
    partial void OnRSI_BOTTOM_STARTChanging(System.Nullable<int> value);
    partial void OnRSI_BOTTOM_STARTChanged();
    partial void OnRSI_BOTTOM_ENDChanging(System.Nullable<int> value);
    partial void OnRSI_BOTTOM_ENDChanged();
    partial void OnRSI_BOTTOM_CURRENTChanging(System.Nullable<int> value);
    partial void OnRSI_BOTTOM_CURRENTChanged();
    partial void OnDMI_PLUS_STARTChanging(System.Nullable<int> value);
    partial void OnDMI_PLUS_STARTChanged();
    partial void OnDMI_PLUS_ENDChanging(System.Nullable<int> value);
    partial void OnDMI_PLUS_ENDChanged();
    partial void OnDMI_PLUS_CURRENTChanging(System.Nullable<int> value);
    partial void OnDMI_PLUS_CURRENTChanged();
    partial void OnDMI_MINUS_STARTChanging(System.Nullable<int> value);
    partial void OnDMI_MINUS_STARTChanged();
    partial void OnDMI_MINUS_ENDChanging(System.Nullable<int> value);
    partial void OnDMI_MINUS_ENDChanged();
    partial void OnDMI_MINUS_CURRENTChanging(System.Nullable<int> value);
    partial void OnDMI_MINUS_CURRENTChanged();
    #endregion
		
		public tblSetting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADX_START", DbType="Int")]
		public System.Nullable<int> ADX_START
		{
			get
			{
				return this._ADX_START;
			}
			set
			{
				if ((this._ADX_START != value))
				{
					this.OnADX_STARTChanging(value);
					this.SendPropertyChanging();
					this._ADX_START = value;
					this.SendPropertyChanged("ADX_START");
					this.OnADX_STARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADX_END", DbType="Int")]
		public System.Nullable<int> ADX_END
		{
			get
			{
				return this._ADX_END;
			}
			set
			{
				if ((this._ADX_END != value))
				{
					this.OnADX_ENDChanging(value);
					this.SendPropertyChanging();
					this._ADX_END = value;
					this.SendPropertyChanged("ADX_END");
					this.OnADX_ENDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADX_CURRENT", DbType="Int")]
		public System.Nullable<int> ADX_CURRENT
		{
			get
			{
				return this._ADX_CURRENT;
			}
			set
			{
				if ((this._ADX_CURRENT != value))
				{
					this.OnADX_CURRENTChanging(value);
					this.SendPropertyChanging();
					this._ADX_CURRENT = value;
					this.SendPropertyChanged("ADX_CURRENT");
					this.OnADX_CURRENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_START", DbType="Int")]
		public System.Nullable<int> RSI_START
		{
			get
			{
				return this._RSI_START;
			}
			set
			{
				if ((this._RSI_START != value))
				{
					this.OnRSI_STARTChanging(value);
					this.SendPropertyChanging();
					this._RSI_START = value;
					this.SendPropertyChanged("RSI_START");
					this.OnRSI_STARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_END", DbType="Int")]
		public System.Nullable<int> RSI_END
		{
			get
			{
				return this._RSI_END;
			}
			set
			{
				if ((this._RSI_END != value))
				{
					this.OnRSI_ENDChanging(value);
					this.SendPropertyChanging();
					this._RSI_END = value;
					this.SendPropertyChanged("RSI_END");
					this.OnRSI_ENDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_CURRENT", DbType="Int")]
		public System.Nullable<int> RSI_CURRENT
		{
			get
			{
				return this._RSI_CURRENT;
			}
			set
			{
				if ((this._RSI_CURRENT != value))
				{
					this.OnRSI_CURRENTChanging(value);
					this.SendPropertyChanging();
					this._RSI_CURRENT = value;
					this.SendPropertyChanged("RSI_CURRENT");
					this.OnRSI_CURRENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMA_1_START", DbType="Float")]
		public System.Nullable<double> MAMA_1_START
		{
			get
			{
				return this._MAMA_1_START;
			}
			set
			{
				if ((this._MAMA_1_START != value))
				{
					this.OnMAMA_1_STARTChanging(value);
					this.SendPropertyChanging();
					this._MAMA_1_START = value;
					this.SendPropertyChanged("MAMA_1_START");
					this.OnMAMA_1_STARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMA_1_END", DbType="Float")]
		public System.Nullable<double> MAMA_1_END
		{
			get
			{
				return this._MAMA_1_END;
			}
			set
			{
				if ((this._MAMA_1_END != value))
				{
					this.OnMAMA_1_ENDChanging(value);
					this.SendPropertyChanging();
					this._MAMA_1_END = value;
					this.SendPropertyChanged("MAMA_1_END");
					this.OnMAMA_1_ENDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMA_1_CURRENT", DbType="Float")]
		public System.Nullable<double> MAMA_1_CURRENT
		{
			get
			{
				return this._MAMA_1_CURRENT;
			}
			set
			{
				if ((this._MAMA_1_CURRENT != value))
				{
					this.OnMAMA_1_CURRENTChanging(value);
					this.SendPropertyChanging();
					this._MAMA_1_CURRENT = value;
					this.SendPropertyChanged("MAMA_1_CURRENT");
					this.OnMAMA_1_CURRENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMA_2_START", DbType="Float")]
		public System.Nullable<double> MAMA_2_START
		{
			get
			{
				return this._MAMA_2_START;
			}
			set
			{
				if ((this._MAMA_2_START != value))
				{
					this.OnMAMA_2_STARTChanging(value);
					this.SendPropertyChanging();
					this._MAMA_2_START = value;
					this.SendPropertyChanged("MAMA_2_START");
					this.OnMAMA_2_STARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMA_2_END", DbType="Float")]
		public System.Nullable<double> MAMA_2_END
		{
			get
			{
				return this._MAMA_2_END;
			}
			set
			{
				if ((this._MAMA_2_END != value))
				{
					this.OnMAMA_2_ENDChanging(value);
					this.SendPropertyChanging();
					this._MAMA_2_END = value;
					this.SendPropertyChanged("MAMA_2_END");
					this.OnMAMA_2_ENDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMA_2_CURRENT", DbType="Float")]
		public System.Nullable<double> MAMA_2_CURRENT
		{
			get
			{
				return this._MAMA_2_CURRENT;
			}
			set
			{
				if ((this._MAMA_2_CURRENT != value))
				{
					this.OnMAMA_2_CURRENTChanging(value);
					this.SendPropertyChanging();
					this._MAMA_2_CURRENT = value;
					this.SendPropertyChanged("MAMA_2_CURRENT");
					this.OnMAMA_2_CURRENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_EMA_START", DbType="Int")]
		public System.Nullable<int> RSI_EMA_START
		{
			get
			{
				return this._RSI_EMA_START;
			}
			set
			{
				if ((this._RSI_EMA_START != value))
				{
					this.OnRSI_EMA_STARTChanging(value);
					this.SendPropertyChanging();
					this._RSI_EMA_START = value;
					this.SendPropertyChanged("RSI_EMA_START");
					this.OnRSI_EMA_STARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_EMA_END", DbType="Int")]
		public System.Nullable<int> RSI_EMA_END
		{
			get
			{
				return this._RSI_EMA_END;
			}
			set
			{
				if ((this._RSI_EMA_END != value))
				{
					this.OnRSI_EMA_ENDChanging(value);
					this.SendPropertyChanging();
					this._RSI_EMA_END = value;
					this.SendPropertyChanged("RSI_EMA_END");
					this.OnRSI_EMA_ENDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_EMA_CURRENT", DbType="Int")]
		public System.Nullable<int> RSI_EMA_CURRENT
		{
			get
			{
				return this._RSI_EMA_CURRENT;
			}
			set
			{
				if ((this._RSI_EMA_CURRENT != value))
				{
					this.OnRSI_EMA_CURRENTChanging(value);
					this.SendPropertyChanging();
					this._RSI_EMA_CURRENT = value;
					this.SendPropertyChanged("RSI_EMA_CURRENT");
					this.OnRSI_EMA_CURRENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_SLOPE_START", DbType="Int")]
		public System.Nullable<int> RSI_SLOPE_START
		{
			get
			{
				return this._RSI_SLOPE_START;
			}
			set
			{
				if ((this._RSI_SLOPE_START != value))
				{
					this.OnRSI_SLOPE_STARTChanging(value);
					this.SendPropertyChanging();
					this._RSI_SLOPE_START = value;
					this.SendPropertyChanged("RSI_SLOPE_START");
					this.OnRSI_SLOPE_STARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_SLOPE_END", DbType="Int")]
		public System.Nullable<int> RSI_SLOPE_END
		{
			get
			{
				return this._RSI_SLOPE_END;
			}
			set
			{
				if ((this._RSI_SLOPE_END != value))
				{
					this.OnRSI_SLOPE_ENDChanging(value);
					this.SendPropertyChanging();
					this._RSI_SLOPE_END = value;
					this.SendPropertyChanged("RSI_SLOPE_END");
					this.OnRSI_SLOPE_ENDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_SLOPE_CURRENT", DbType="Int")]
		public System.Nullable<int> RSI_SLOPE_CURRENT
		{
			get
			{
				return this._RSI_SLOPE_CURRENT;
			}
			set
			{
				if ((this._RSI_SLOPE_CURRENT != value))
				{
					this.OnRSI_SLOPE_CURRENTChanging(value);
					this.SendPropertyChanging();
					this._RSI_SLOPE_CURRENT = value;
					this.SendPropertyChanged("RSI_SLOPE_CURRENT");
					this.OnRSI_SLOPE_CURRENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_TOP_START", DbType="Int")]
		public System.Nullable<int> RSI_TOP_START
		{
			get
			{
				return this._RSI_TOP_START;
			}
			set
			{
				if ((this._RSI_TOP_START != value))
				{
					this.OnRSI_TOP_STARTChanging(value);
					this.SendPropertyChanging();
					this._RSI_TOP_START = value;
					this.SendPropertyChanged("RSI_TOP_START");
					this.OnRSI_TOP_STARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_TOP_END", DbType="Int")]
		public System.Nullable<int> RSI_TOP_END
		{
			get
			{
				return this._RSI_TOP_END;
			}
			set
			{
				if ((this._RSI_TOP_END != value))
				{
					this.OnRSI_TOP_ENDChanging(value);
					this.SendPropertyChanging();
					this._RSI_TOP_END = value;
					this.SendPropertyChanged("RSI_TOP_END");
					this.OnRSI_TOP_ENDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_TOP_CURRENT", DbType="Int")]
		public System.Nullable<int> RSI_TOP_CURRENT
		{
			get
			{
				return this._RSI_TOP_CURRENT;
			}
			set
			{
				if ((this._RSI_TOP_CURRENT != value))
				{
					this.OnRSI_TOP_CURRENTChanging(value);
					this.SendPropertyChanging();
					this._RSI_TOP_CURRENT = value;
					this.SendPropertyChanged("RSI_TOP_CURRENT");
					this.OnRSI_TOP_CURRENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_BOTTOM_START", DbType="Int")]
		public System.Nullable<int> RSI_BOTTOM_START
		{
			get
			{
				return this._RSI_BOTTOM_START;
			}
			set
			{
				if ((this._RSI_BOTTOM_START != value))
				{
					this.OnRSI_BOTTOM_STARTChanging(value);
					this.SendPropertyChanging();
					this._RSI_BOTTOM_START = value;
					this.SendPropertyChanged("RSI_BOTTOM_START");
					this.OnRSI_BOTTOM_STARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_BOTTOM_END", DbType="Int")]
		public System.Nullable<int> RSI_BOTTOM_END
		{
			get
			{
				return this._RSI_BOTTOM_END;
			}
			set
			{
				if ((this._RSI_BOTTOM_END != value))
				{
					this.OnRSI_BOTTOM_ENDChanging(value);
					this.SendPropertyChanging();
					this._RSI_BOTTOM_END = value;
					this.SendPropertyChanged("RSI_BOTTOM_END");
					this.OnRSI_BOTTOM_ENDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_BOTTOM_CURRENT", DbType="Int")]
		public System.Nullable<int> RSI_BOTTOM_CURRENT
		{
			get
			{
				return this._RSI_BOTTOM_CURRENT;
			}
			set
			{
				if ((this._RSI_BOTTOM_CURRENT != value))
				{
					this.OnRSI_BOTTOM_CURRENTChanging(value);
					this.SendPropertyChanging();
					this._RSI_BOTTOM_CURRENT = value;
					this.SendPropertyChanged("RSI_BOTTOM_CURRENT");
					this.OnRSI_BOTTOM_CURRENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DMI_PLUS_START", DbType="Int")]
		public System.Nullable<int> DMI_PLUS_START
		{
			get
			{
				return this._DMI_PLUS_START;
			}
			set
			{
				if ((this._DMI_PLUS_START != value))
				{
					this.OnDMI_PLUS_STARTChanging(value);
					this.SendPropertyChanging();
					this._DMI_PLUS_START = value;
					this.SendPropertyChanged("DMI_PLUS_START");
					this.OnDMI_PLUS_STARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DMI_PLUS_END", DbType="Int")]
		public System.Nullable<int> DMI_PLUS_END
		{
			get
			{
				return this._DMI_PLUS_END;
			}
			set
			{
				if ((this._DMI_PLUS_END != value))
				{
					this.OnDMI_PLUS_ENDChanging(value);
					this.SendPropertyChanging();
					this._DMI_PLUS_END = value;
					this.SendPropertyChanged("DMI_PLUS_END");
					this.OnDMI_PLUS_ENDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DMI_PLUS_CURRENT", DbType="Int")]
		public System.Nullable<int> DMI_PLUS_CURRENT
		{
			get
			{
				return this._DMI_PLUS_CURRENT;
			}
			set
			{
				if ((this._DMI_PLUS_CURRENT != value))
				{
					this.OnDMI_PLUS_CURRENTChanging(value);
					this.SendPropertyChanging();
					this._DMI_PLUS_CURRENT = value;
					this.SendPropertyChanged("DMI_PLUS_CURRENT");
					this.OnDMI_PLUS_CURRENTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DMI_MINUS_START", DbType="Int")]
		public System.Nullable<int> DMI_MINUS_START
		{
			get
			{
				return this._DMI_MINUS_START;
			}
			set
			{
				if ((this._DMI_MINUS_START != value))
				{
					this.OnDMI_MINUS_STARTChanging(value);
					this.SendPropertyChanging();
					this._DMI_MINUS_START = value;
					this.SendPropertyChanged("DMI_MINUS_START");
					this.OnDMI_MINUS_STARTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DMI_MINUS_END", DbType="Int")]
		public System.Nullable<int> DMI_MINUS_END
		{
			get
			{
				return this._DMI_MINUS_END;
			}
			set
			{
				if ((this._DMI_MINUS_END != value))
				{
					this.OnDMI_MINUS_ENDChanging(value);
					this.SendPropertyChanging();
					this._DMI_MINUS_END = value;
					this.SendPropertyChanged("DMI_MINUS_END");
					this.OnDMI_MINUS_ENDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DMI_MINUS_CURRENT", DbType="Int")]
		public System.Nullable<int> DMI_MINUS_CURRENT
		{
			get
			{
				return this._DMI_MINUS_CURRENT;
			}
			set
			{
				if ((this._DMI_MINUS_CURRENT != value))
				{
					this.OnDMI_MINUS_CURRENTChanging(value);
					this.SendPropertyChanging();
					this._DMI_MINUS_CURRENT = value;
					this.SendPropertyChanged("DMI_MINUS_CURRENT");
					this.OnDMI_MINUS_CURRENTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl5Minute")]
	public partial class tbl5Minute : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private System.Nullable<int> _Profit;
		
		private System.Nullable<int> _ADX;
		
		private System.Nullable<int> _RSI;
		
		private System.Nullable<double> _MAMA_1;
		
		private System.Nullable<double> _MAMA_2;
		
		private System.Nullable<int> _RSI_EMA;
		
		private System.Nullable<int> _RSI_SLOPE;
		
		private System.Nullable<int> _RSI_TOP;
		
		private System.Nullable<int> _RSI_BOTTOM;
		
		private System.Nullable<int> _DMI_PLUS;
		
		private System.Nullable<int> _DMI_MINUS;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnProfitChanging(System.Nullable<int> value);
    partial void OnProfitChanged();
    partial void OnADXChanging(System.Nullable<int> value);
    partial void OnADXChanged();
    partial void OnRSIChanging(System.Nullable<int> value);
    partial void OnRSIChanged();
    partial void OnMAMA_1Changing(System.Nullable<double> value);
    partial void OnMAMA_1Changed();
    partial void OnMAMA_2Changing(System.Nullable<double> value);
    partial void OnMAMA_2Changed();
    partial void OnRSI_EMAChanging(System.Nullable<int> value);
    partial void OnRSI_EMAChanged();
    partial void OnRSI_SLOPEChanging(System.Nullable<int> value);
    partial void OnRSI_SLOPEChanged();
    partial void OnRSI_TOPChanging(System.Nullable<int> value);
    partial void OnRSI_TOPChanged();
    partial void OnRSI_BOTTOMChanging(System.Nullable<int> value);
    partial void OnRSI_BOTTOMChanged();
    partial void OnDMI_PLUSChanging(System.Nullable<int> value);
    partial void OnDMI_PLUSChanged();
    partial void OnDMI_MINUSChanging(System.Nullable<int> value);
    partial void OnDMI_MINUSChanged();
    #endregion
		
		public tbl5Minute()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Profit", DbType="Int")]
		public System.Nullable<int> Profit
		{
			get
			{
				return this._Profit;
			}
			set
			{
				if ((this._Profit != value))
				{
					this.OnProfitChanging(value);
					this.SendPropertyChanging();
					this._Profit = value;
					this.SendPropertyChanged("Profit");
					this.OnProfitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADX", DbType="Int")]
		public System.Nullable<int> ADX
		{
			get
			{
				return this._ADX;
			}
			set
			{
				if ((this._ADX != value))
				{
					this.OnADXChanging(value);
					this.SendPropertyChanging();
					this._ADX = value;
					this.SendPropertyChanged("ADX");
					this.OnADXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI", DbType="Int")]
		public System.Nullable<int> RSI
		{
			get
			{
				return this._RSI;
			}
			set
			{
				if ((this._RSI != value))
				{
					this.OnRSIChanging(value);
					this.SendPropertyChanging();
					this._RSI = value;
					this.SendPropertyChanged("RSI");
					this.OnRSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMA_1", DbType="Float")]
		public System.Nullable<double> MAMA_1
		{
			get
			{
				return this._MAMA_1;
			}
			set
			{
				if ((this._MAMA_1 != value))
				{
					this.OnMAMA_1Changing(value);
					this.SendPropertyChanging();
					this._MAMA_1 = value;
					this.SendPropertyChanged("MAMA_1");
					this.OnMAMA_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAMA_2", DbType="Float")]
		public System.Nullable<double> MAMA_2
		{
			get
			{
				return this._MAMA_2;
			}
			set
			{
				if ((this._MAMA_2 != value))
				{
					this.OnMAMA_2Changing(value);
					this.SendPropertyChanging();
					this._MAMA_2 = value;
					this.SendPropertyChanged("MAMA_2");
					this.OnMAMA_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_EMA", DbType="Int")]
		public System.Nullable<int> RSI_EMA
		{
			get
			{
				return this._RSI_EMA;
			}
			set
			{
				if ((this._RSI_EMA != value))
				{
					this.OnRSI_EMAChanging(value);
					this.SendPropertyChanging();
					this._RSI_EMA = value;
					this.SendPropertyChanged("RSI_EMA");
					this.OnRSI_EMAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_SLOPE", DbType="Int")]
		public System.Nullable<int> RSI_SLOPE
		{
			get
			{
				return this._RSI_SLOPE;
			}
			set
			{
				if ((this._RSI_SLOPE != value))
				{
					this.OnRSI_SLOPEChanging(value);
					this.SendPropertyChanging();
					this._RSI_SLOPE = value;
					this.SendPropertyChanged("RSI_SLOPE");
					this.OnRSI_SLOPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_TOP", DbType="Int")]
		public System.Nullable<int> RSI_TOP
		{
			get
			{
				return this._RSI_TOP;
			}
			set
			{
				if ((this._RSI_TOP != value))
				{
					this.OnRSI_TOPChanging(value);
					this.SendPropertyChanging();
					this._RSI_TOP = value;
					this.SendPropertyChanged("RSI_TOP");
					this.OnRSI_TOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RSI_BOTTOM", DbType="Int")]
		public System.Nullable<int> RSI_BOTTOM
		{
			get
			{
				return this._RSI_BOTTOM;
			}
			set
			{
				if ((this._RSI_BOTTOM != value))
				{
					this.OnRSI_BOTTOMChanging(value);
					this.SendPropertyChanging();
					this._RSI_BOTTOM = value;
					this.SendPropertyChanged("RSI_BOTTOM");
					this.OnRSI_BOTTOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DMI_PLUS", DbType="Int")]
		public System.Nullable<int> DMI_PLUS
		{
			get
			{
				return this._DMI_PLUS;
			}
			set
			{
				if ((this._DMI_PLUS != value))
				{
					this.OnDMI_PLUSChanging(value);
					this.SendPropertyChanging();
					this._DMI_PLUS = value;
					this.SendPropertyChanged("DMI_PLUS");
					this.OnDMI_PLUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DMI_MINUS", DbType="Int")]
		public System.Nullable<int> DMI_MINUS
		{
			get
			{
				return this._DMI_MINUS;
			}
			set
			{
				if ((this._DMI_MINUS != value))
				{
					this.OnDMI_MINUSChanging(value);
					this.SendPropertyChanging();
					this._DMI_MINUS = value;
					this.SendPropertyChanged("DMI_MINUS");
					this.OnDMI_MINUSChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
