#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlsiUtils
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AlsiTM")]
	public partial class AlsiTMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblUser(tblUser instance);
    partial void UpdatetblUser(tblUser instance);
    partial void DeletetblUser(tblUser instance);
    partial void InserttblLog(tblLog instance);
    partial void UpdatetblLog(tblLog instance);
    partial void DeletetblLog(tblLog instance);
    #endregion
		
		public AlsiTMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlsiTMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlsiTMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AlsiTMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblUser> tblUsers
		{
			get
			{
				return this.GetTable<tblUser>();
			}
		}
		
		public System.Data.Linq.Table<tblLog> tblLogs
		{
			get
			{
				return this.GetTable<tblLog>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Pieter.tblUser")]
	public partial class tblUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _USER_NAME;
		
		private string _USER_MACADRESS;
		
		private System.Nullable<System.DateTime> _USER_EXPIRY;
		
		private System.Nullable<bool> _USER_ADMIN;
		
		private System.Nullable<bool> _USER_LIVE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnUSER_NAMEChanging(string value);
    partial void OnUSER_NAMEChanged();
    partial void OnUSER_MACADRESSChanging(string value);
    partial void OnUSER_MACADRESSChanged();
    partial void OnUSER_EXPIRYChanging(System.Nullable<System.DateTime> value);
    partial void OnUSER_EXPIRYChanged();
    partial void OnUSER_ADMINChanging(System.Nullable<bool> value);
    partial void OnUSER_ADMINChanged();
    partial void OnUSER_LIVEChanging(System.Nullable<bool> value);
    partial void OnUSER_LIVEChanged();
    #endregion
		
		public tblUser()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_NAME", DbType="VarChar(50)")]
		public string USER_NAME
		{
			get
			{
				return this._USER_NAME;
			}
			set
			{
				if ((this._USER_NAME != value))
				{
					this.OnUSER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._USER_NAME = value;
					this.SendPropertyChanged("USER_NAME");
					this.OnUSER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_MACADRESS", DbType="VarChar(50)")]
		public string USER_MACADRESS
		{
			get
			{
				return this._USER_MACADRESS;
			}
			set
			{
				if ((this._USER_MACADRESS != value))
				{
					this.OnUSER_MACADRESSChanging(value);
					this.SendPropertyChanging();
					this._USER_MACADRESS = value;
					this.SendPropertyChanged("USER_MACADRESS");
					this.OnUSER_MACADRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_EXPIRY", DbType="DateTime")]
		public System.Nullable<System.DateTime> USER_EXPIRY
		{
			get
			{
				return this._USER_EXPIRY;
			}
			set
			{
				if ((this._USER_EXPIRY != value))
				{
					this.OnUSER_EXPIRYChanging(value);
					this.SendPropertyChanging();
					this._USER_EXPIRY = value;
					this.SendPropertyChanged("USER_EXPIRY");
					this.OnUSER_EXPIRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_ADMIN", DbType="Bit")]
		public System.Nullable<bool> USER_ADMIN
		{
			get
			{
				return this._USER_ADMIN;
			}
			set
			{
				if ((this._USER_ADMIN != value))
				{
					this.OnUSER_ADMINChanging(value);
					this.SendPropertyChanging();
					this._USER_ADMIN = value;
					this.SendPropertyChanged("USER_ADMIN");
					this.OnUSER_ADMINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USER_LIVE", DbType="Bit")]
		public System.Nullable<bool> USER_LIVE
		{
			get
			{
				return this._USER_LIVE;
			}
			set
			{
				if ((this._USER_LIVE != value))
				{
					this.OnUSER_LIVEChanging(value);
					this.SendPropertyChanging();
					this._USER_LIVE = value;
					this.SendPropertyChanged("USER_LIVE");
					this.OnUSER_LIVEChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="Pieter.tblLog")]
	public partial class tblLog : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LOG_ID;
		
		private System.Nullable<System.DateTime> _LOG_TS;
		
		private System.Nullable<int> _LOG_USER_ID;
		
		private string _LOG_VERSION;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLOG_IDChanging(int value);
    partial void OnLOG_IDChanged();
    partial void OnLOG_TSChanging(System.Nullable<System.DateTime> value);
    partial void OnLOG_TSChanged();
    partial void OnLOG_USER_IDChanging(System.Nullable<int> value);
    partial void OnLOG_USER_IDChanged();
    partial void OnLOG_VERSIONChanging(string value);
    partial void OnLOG_VERSIONChanged();
    #endregion
		
		public tblLog()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOG_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LOG_ID
		{
			get
			{
				return this._LOG_ID;
			}
			set
			{
				if ((this._LOG_ID != value))
				{
					this.OnLOG_IDChanging(value);
					this.SendPropertyChanging();
					this._LOG_ID = value;
					this.SendPropertyChanged("LOG_ID");
					this.OnLOG_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOG_TS", DbType="DateTime")]
		public System.Nullable<System.DateTime> LOG_TS
		{
			get
			{
				return this._LOG_TS;
			}
			set
			{
				if ((this._LOG_TS != value))
				{
					this.OnLOG_TSChanging(value);
					this.SendPropertyChanging();
					this._LOG_TS = value;
					this.SendPropertyChanged("LOG_TS");
					this.OnLOG_TSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOG_USER_ID", DbType="Int")]
		public System.Nullable<int> LOG_USER_ID
		{
			get
			{
				return this._LOG_USER_ID;
			}
			set
			{
				if ((this._LOG_USER_ID != value))
				{
					this.OnLOG_USER_IDChanging(value);
					this.SendPropertyChanging();
					this._LOG_USER_ID = value;
					this.SendPropertyChanged("LOG_USER_ID");
					this.OnLOG_USER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOG_VERSION", DbType="VarChar(10)")]
		public string LOG_VERSION
		{
			get
			{
				return this._LOG_VERSION;
			}
			set
			{
				if ((this._LOG_VERSION != value))
				{
					this.OnLOG_VERSIONChanging(value);
					this.SendPropertyChanging();
					this._LOG_VERSION = value;
					this.SendPropertyChanged("LOG_VERSION");
					this.OnLOG_VERSIONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
