<?xml version="1.0" encoding="utf-8"?><Database Name="AlsiTM" Class="AlsiTMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="Pieter.tblLog" Member="tblLogs">
    <Type Name="tblLog">
      <Column Name="LOG_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LOG_TS" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LOG_USER_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOG_VERSION" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Pieter.tblUser" Member="tblUsers">
    <Type Name="tblUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="USER_NAME" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_MACADRESS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USER_EXPIRY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="USER_ADMIN" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="USER_LIVE" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblUser_tblMessageUser" Member="tblMessageUsers" ThisKey="ID" OtherKey="MSG_USER_FROM" Type="tblMessageUser" />
      <Association Name="tblUser_tblMessageUser1" Member="tblMessageUsers1" ThisKey="ID" OtherKey="MSG_USER_TO" Type="tblMessageUser" />
    </Type>
  </Table>
  <Table Name="Pieter.tblMessageUser" Member="tblMessageUsers">
    <Type Name="tblMessageUser">
      <Column Name="MSG_USER_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MSG_USER_FROM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MSG_USER_TO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MSG_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblUser_tblMessageUser" Member="tblUser" ThisKey="MSG_USER_FROM" OtherKey="ID" Type="tblUser" IsForeignKey="true" />
      <Association Name="tblUser_tblMessageUser1" Member="tblUser1" ThisKey="MSG_USER_TO" OtherKey="ID" Type="tblUser" IsForeignKey="true" />
      <Association Name="tblMessage_tblMessageUser" Member="tblMessage" ThisKey="MSG_ID" OtherKey="TBL_MSG_ID" Type="tblMessage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Pieter.tblMessage" Member="tblMessages">
    <Type Name="tblMessage">
      <Column Name="TBL_MSG_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TBL_MSG_TEXT" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="TBL_MSG_TIME" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tblMessage_tblMessageUser" Member="tblMessageUsers" ThisKey="TBL_MSG_ID" OtherKey="MSG_ID" Type="tblMessageUser" />
    </Type>
  </Table>
</Database>