#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlsiUtils
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="emaSim")]
	public partial class SimDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl5Min(tbl5Min instance);
    partial void Updatetbl5Min(tbl5Min instance);
    partial void Deletetbl5Min(tbl5Min instance);
    partial void Inserttbl2Min(tbl2Min instance);
    partial void Updatetbl2Min(tbl2Min instance);
    partial void Deletetbl2Min(tbl2Min instance);
    partial void InsertTProf(TProf instance);
    partial void UpdateTProf(TProf instance);
    partial void DeleteTProf(TProf instance);
    #endregion
		
		public SimDBDataContext() : 
				base(global::AlsiUtils.Properties.Settings.Default.emaSimConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SimDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SimDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SimDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SimDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl5Min> tbl5Mins
		{
			get
			{
				return this.GetTable<tbl5Min>();
			}
		}
		
		public System.Data.Linq.Table<tbl2Min> tbl2Mins
		{
			get
			{
				return this.GetTable<tbl2Min>();
			}
		}
		
		public System.Data.Linq.Table<TProf> TProfs
		{
			get
			{
				return this.GetTable<TProf>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl5Min")]
	public partial class tbl5Min : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Count;
		
		private System.Nullable<int> _Trades;
		
		private System.Nullable<int> _TotalPL;
		
		private System.Nullable<decimal> _AvgPL;
		
		private System.Nullable<decimal> _Win;
		
		private System.Nullable<decimal> _Loose;
		
		private System.Nullable<int> _E_A1;
		
		private System.Nullable<int> _E_A2;
		
		private System.Nullable<int> _E_B1;
		
		private System.Nullable<int> _E_B2;
		
		private System.Nullable<int> _E_C;
		
		private System.Nullable<int> _Period;
		
		private string _CloseEndDay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCountChanging(int value);
    partial void OnCountChanged();
    partial void OnTradesChanging(System.Nullable<int> value);
    partial void OnTradesChanged();
    partial void OnTotalPLChanging(System.Nullable<int> value);
    partial void OnTotalPLChanged();
    partial void OnAvgPLChanging(System.Nullable<decimal> value);
    partial void OnAvgPLChanged();
    partial void OnWinChanging(System.Nullable<decimal> value);
    partial void OnWinChanged();
    partial void OnLooseChanging(System.Nullable<decimal> value);
    partial void OnLooseChanged();
    partial void OnE_A1Changing(System.Nullable<int> value);
    partial void OnE_A1Changed();
    partial void OnE_A2Changing(System.Nullable<int> value);
    partial void OnE_A2Changed();
    partial void OnE_B1Changing(System.Nullable<int> value);
    partial void OnE_B1Changed();
    partial void OnE_B2Changing(System.Nullable<int> value);
    partial void OnE_B2Changed();
    partial void OnE_CChanging(System.Nullable<int> value);
    partial void OnE_CChanged();
    partial void OnPeriodChanging(System.Nullable<int> value);
    partial void OnPeriodChanged();
    partial void OnCloseEndDayChanging(string value);
    partial void OnCloseEndDayChanged();
    #endregion
		
		public tbl5Min()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Count
		{
			get
			{
				return this._Count;
			}
			set
			{
				if ((this._Count != value))
				{
					this.OnCountChanging(value);
					this.SendPropertyChanging();
					this._Count = value;
					this.SendPropertyChanged("Count");
					this.OnCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trades", DbType="Int")]
		public System.Nullable<int> Trades
		{
			get
			{
				return this._Trades;
			}
			set
			{
				if ((this._Trades != value))
				{
					this.OnTradesChanging(value);
					this.SendPropertyChanging();
					this._Trades = value;
					this.SendPropertyChanged("Trades");
					this.OnTradesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalPL", DbType="Int")]
		public System.Nullable<int> TotalPL
		{
			get
			{
				return this._TotalPL;
			}
			set
			{
				if ((this._TotalPL != value))
				{
					this.OnTotalPLChanging(value);
					this.SendPropertyChanging();
					this._TotalPL = value;
					this.SendPropertyChanged("TotalPL");
					this.OnTotalPLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgPL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> AvgPL
		{
			get
			{
				return this._AvgPL;
			}
			set
			{
				if ((this._AvgPL != value))
				{
					this.OnAvgPLChanging(value);
					this.SendPropertyChanging();
					this._AvgPL = value;
					this.SendPropertyChanged("AvgPL");
					this.OnAvgPLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Win", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Win
		{
			get
			{
				return this._Win;
			}
			set
			{
				if ((this._Win != value))
				{
					this.OnWinChanging(value);
					this.SendPropertyChanging();
					this._Win = value;
					this.SendPropertyChanged("Win");
					this.OnWinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loose", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Loose
		{
			get
			{
				return this._Loose;
			}
			set
			{
				if ((this._Loose != value))
				{
					this.OnLooseChanging(value);
					this.SendPropertyChanging();
					this._Loose = value;
					this.SendPropertyChanged("Loose");
					this.OnLooseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_A1", DbType="Int")]
		public System.Nullable<int> E_A1
		{
			get
			{
				return this._E_A1;
			}
			set
			{
				if ((this._E_A1 != value))
				{
					this.OnE_A1Changing(value);
					this.SendPropertyChanging();
					this._E_A1 = value;
					this.SendPropertyChanged("E_A1");
					this.OnE_A1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_A2", DbType="Int")]
		public System.Nullable<int> E_A2
		{
			get
			{
				return this._E_A2;
			}
			set
			{
				if ((this._E_A2 != value))
				{
					this.OnE_A2Changing(value);
					this.SendPropertyChanging();
					this._E_A2 = value;
					this.SendPropertyChanged("E_A2");
					this.OnE_A2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_B1", DbType="Int")]
		public System.Nullable<int> E_B1
		{
			get
			{
				return this._E_B1;
			}
			set
			{
				if ((this._E_B1 != value))
				{
					this.OnE_B1Changing(value);
					this.SendPropertyChanging();
					this._E_B1 = value;
					this.SendPropertyChanged("E_B1");
					this.OnE_B1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_B2", DbType="Int")]
		public System.Nullable<int> E_B2
		{
			get
			{
				return this._E_B2;
			}
			set
			{
				if ((this._E_B2 != value))
				{
					this.OnE_B2Changing(value);
					this.SendPropertyChanging();
					this._E_B2 = value;
					this.SendPropertyChanged("E_B2");
					this.OnE_B2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_C", DbType="Int")]
		public System.Nullable<int> E_C
		{
			get
			{
				return this._E_C;
			}
			set
			{
				if ((this._E_C != value))
				{
					this.OnE_CChanging(value);
					this.SendPropertyChanging();
					this._E_C = value;
					this.SendPropertyChanged("E_C");
					this.OnE_CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period", DbType="Int")]
		public System.Nullable<int> Period
		{
			get
			{
				return this._Period;
			}
			set
			{
				if ((this._Period != value))
				{
					this.OnPeriodChanging(value);
					this.SendPropertyChanging();
					this._Period = value;
					this.SendPropertyChanged("Period");
					this.OnPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CloseEndDay", DbType="VarChar(5)")]
		public string CloseEndDay
		{
			get
			{
				return this._CloseEndDay;
			}
			set
			{
				if ((this._CloseEndDay != value))
				{
					this.OnCloseEndDayChanging(value);
					this.SendPropertyChanging();
					this._CloseEndDay = value;
					this.SendPropertyChanged("CloseEndDay");
					this.OnCloseEndDayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl2Min")]
	public partial class tbl2Min : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Count;
		
		private System.Nullable<int> _Trades;
		
		private System.Nullable<int> _TotalPL;
		
		private System.Nullable<decimal> _AvgPL;
		
		private System.Nullable<decimal> _Win;
		
		private System.Nullable<decimal> _Loose;
		
		private System.Nullable<int> _E_A1;
		
		private System.Nullable<int> _E_A2;
		
		private System.Nullable<int> _E_B1;
		
		private System.Nullable<int> _E_B2;
		
		private System.Nullable<int> _E_C;
		
		private System.Nullable<int> _Period;
		
		private string _CloseEndDay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCountChanging(int value);
    partial void OnCountChanged();
    partial void OnTradesChanging(System.Nullable<int> value);
    partial void OnTradesChanged();
    partial void OnTotalPLChanging(System.Nullable<int> value);
    partial void OnTotalPLChanged();
    partial void OnAvgPLChanging(System.Nullable<decimal> value);
    partial void OnAvgPLChanged();
    partial void OnWinChanging(System.Nullable<decimal> value);
    partial void OnWinChanged();
    partial void OnLooseChanging(System.Nullable<decimal> value);
    partial void OnLooseChanged();
    partial void OnE_A1Changing(System.Nullable<int> value);
    partial void OnE_A1Changed();
    partial void OnE_A2Changing(System.Nullable<int> value);
    partial void OnE_A2Changed();
    partial void OnE_B1Changing(System.Nullable<int> value);
    partial void OnE_B1Changed();
    partial void OnE_B2Changing(System.Nullable<int> value);
    partial void OnE_B2Changed();
    partial void OnE_CChanging(System.Nullable<int> value);
    partial void OnE_CChanged();
    partial void OnPeriodChanging(System.Nullable<int> value);
    partial void OnPeriodChanged();
    partial void OnCloseEndDayChanging(string value);
    partial void OnCloseEndDayChanged();
    #endregion
		
		public tbl2Min()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Count
		{
			get
			{
				return this._Count;
			}
			set
			{
				if ((this._Count != value))
				{
					this.OnCountChanging(value);
					this.SendPropertyChanging();
					this._Count = value;
					this.SendPropertyChanged("Count");
					this.OnCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trades", DbType="Int")]
		public System.Nullable<int> Trades
		{
			get
			{
				return this._Trades;
			}
			set
			{
				if ((this._Trades != value))
				{
					this.OnTradesChanging(value);
					this.SendPropertyChanging();
					this._Trades = value;
					this.SendPropertyChanged("Trades");
					this.OnTradesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalPL", DbType="Int")]
		public System.Nullable<int> TotalPL
		{
			get
			{
				return this._TotalPL;
			}
			set
			{
				if ((this._TotalPL != value))
				{
					this.OnTotalPLChanging(value);
					this.SendPropertyChanging();
					this._TotalPL = value;
					this.SendPropertyChanged("TotalPL");
					this.OnTotalPLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgPL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> AvgPL
		{
			get
			{
				return this._AvgPL;
			}
			set
			{
				if ((this._AvgPL != value))
				{
					this.OnAvgPLChanging(value);
					this.SendPropertyChanging();
					this._AvgPL = value;
					this.SendPropertyChanged("AvgPL");
					this.OnAvgPLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Win", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Win
		{
			get
			{
				return this._Win;
			}
			set
			{
				if ((this._Win != value))
				{
					this.OnWinChanging(value);
					this.SendPropertyChanging();
					this._Win = value;
					this.SendPropertyChanged("Win");
					this.OnWinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loose", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Loose
		{
			get
			{
				return this._Loose;
			}
			set
			{
				if ((this._Loose != value))
				{
					this.OnLooseChanging(value);
					this.SendPropertyChanging();
					this._Loose = value;
					this.SendPropertyChanged("Loose");
					this.OnLooseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_A1", DbType="Int")]
		public System.Nullable<int> E_A1
		{
			get
			{
				return this._E_A1;
			}
			set
			{
				if ((this._E_A1 != value))
				{
					this.OnE_A1Changing(value);
					this.SendPropertyChanging();
					this._E_A1 = value;
					this.SendPropertyChanged("E_A1");
					this.OnE_A1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_A2", DbType="Int")]
		public System.Nullable<int> E_A2
		{
			get
			{
				return this._E_A2;
			}
			set
			{
				if ((this._E_A2 != value))
				{
					this.OnE_A2Changing(value);
					this.SendPropertyChanging();
					this._E_A2 = value;
					this.SendPropertyChanged("E_A2");
					this.OnE_A2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_B1", DbType="Int")]
		public System.Nullable<int> E_B1
		{
			get
			{
				return this._E_B1;
			}
			set
			{
				if ((this._E_B1 != value))
				{
					this.OnE_B1Changing(value);
					this.SendPropertyChanging();
					this._E_B1 = value;
					this.SendPropertyChanged("E_B1");
					this.OnE_B1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_B2", DbType="Int")]
		public System.Nullable<int> E_B2
		{
			get
			{
				return this._E_B2;
			}
			set
			{
				if ((this._E_B2 != value))
				{
					this.OnE_B2Changing(value);
					this.SendPropertyChanging();
					this._E_B2 = value;
					this.SendPropertyChanged("E_B2");
					this.OnE_B2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_C", DbType="Int")]
		public System.Nullable<int> E_C
		{
			get
			{
				return this._E_C;
			}
			set
			{
				if ((this._E_C != value))
				{
					this.OnE_CChanging(value);
					this.SendPropertyChanging();
					this._E_C = value;
					this.SendPropertyChanged("E_C");
					this.OnE_CChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Period", DbType="Int")]
		public System.Nullable<int> Period
		{
			get
			{
				return this._Period;
			}
			set
			{
				if ((this._Period != value))
				{
					this.OnPeriodChanging(value);
					this.SendPropertyChanging();
					this._Period = value;
					this.SendPropertyChanged("Period");
					this.OnPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CloseEndDay", DbType="VarChar(5)")]
		public string CloseEndDay
		{
			get
			{
				return this._CloseEndDay;
			}
			set
			{
				if ((this._CloseEndDay != value))
				{
					this.OnCloseEndDayChanging(value);
					this.SendPropertyChanging();
					this._CloseEndDay = value;
					this.SendPropertyChanged("CloseEndDay");
					this.OnCloseEndDayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TProf")]
	public partial class TProf : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Count;
		
		private System.Nullable<int> _Trades;
		
		private System.Nullable<int> _TotalPL;
		
		private System.Nullable<decimal> _AvgPL;
		
		private System.Nullable<decimal> _Win;
		
		private System.Nullable<decimal> _Loose;
		
		private System.Nullable<int> _SK;
		
		private System.Nullable<int> _FK;
		
		private System.Nullable<int> _D;
		
		private System.Nullable<int> _H;
		
		private System.Nullable<int> _L;
		
		private string _Note;
		
		private string _CloseEndDay;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCountChanging(int value);
    partial void OnCountChanged();
    partial void OnTradesChanging(System.Nullable<int> value);
    partial void OnTradesChanged();
    partial void OnTotalPLChanging(System.Nullable<int> value);
    partial void OnTotalPLChanged();
    partial void OnAvgPLChanging(System.Nullable<decimal> value);
    partial void OnAvgPLChanged();
    partial void OnWinChanging(System.Nullable<decimal> value);
    partial void OnWinChanged();
    partial void OnLooseChanging(System.Nullable<decimal> value);
    partial void OnLooseChanged();
    partial void OnSKChanging(System.Nullable<int> value);
    partial void OnSKChanged();
    partial void OnFKChanging(System.Nullable<int> value);
    partial void OnFKChanged();
    partial void OnDChanging(System.Nullable<int> value);
    partial void OnDChanged();
    partial void OnHChanging(System.Nullable<int> value);
    partial void OnHChanged();
    partial void OnLChanging(System.Nullable<int> value);
    partial void OnLChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnCloseEndDayChanging(string value);
    partial void OnCloseEndDayChanged();
    #endregion
		
		public TProf()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Count", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Count
		{
			get
			{
				return this._Count;
			}
			set
			{
				if ((this._Count != value))
				{
					this.OnCountChanging(value);
					this.SendPropertyChanging();
					this._Count = value;
					this.SendPropertyChanged("Count");
					this.OnCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trades", DbType="Int")]
		public System.Nullable<int> Trades
		{
			get
			{
				return this._Trades;
			}
			set
			{
				if ((this._Trades != value))
				{
					this.OnTradesChanging(value);
					this.SendPropertyChanging();
					this._Trades = value;
					this.SendPropertyChanged("Trades");
					this.OnTradesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalPL", DbType="Int")]
		public System.Nullable<int> TotalPL
		{
			get
			{
				return this._TotalPL;
			}
			set
			{
				if ((this._TotalPL != value))
				{
					this.OnTotalPLChanging(value);
					this.SendPropertyChanging();
					this._TotalPL = value;
					this.SendPropertyChanged("TotalPL");
					this.OnTotalPLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvgPL", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> AvgPL
		{
			get
			{
				return this._AvgPL;
			}
			set
			{
				if ((this._AvgPL != value))
				{
					this.OnAvgPLChanging(value);
					this.SendPropertyChanging();
					this._AvgPL = value;
					this.SendPropertyChanged("AvgPL");
					this.OnAvgPLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Win", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Win
		{
			get
			{
				return this._Win;
			}
			set
			{
				if ((this._Win != value))
				{
					this.OnWinChanging(value);
					this.SendPropertyChanging();
					this._Win = value;
					this.SendPropertyChanged("Win");
					this.OnWinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loose", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Loose
		{
			get
			{
				return this._Loose;
			}
			set
			{
				if ((this._Loose != value))
				{
					this.OnLooseChanging(value);
					this.SendPropertyChanging();
					this._Loose = value;
					this.SendPropertyChanged("Loose");
					this.OnLooseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SK", DbType="Int")]
		public System.Nullable<int> SK
		{
			get
			{
				return this._SK;
			}
			set
			{
				if ((this._SK != value))
				{
					this.OnSKChanging(value);
					this.SendPropertyChanging();
					this._SK = value;
					this.SendPropertyChanged("SK");
					this.OnSKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK", DbType="Int")]
		public System.Nullable<int> FK
		{
			get
			{
				return this._FK;
			}
			set
			{
				if ((this._FK != value))
				{
					this.OnFKChanging(value);
					this.SendPropertyChanging();
					this._FK = value;
					this.SendPropertyChanged("FK");
					this.OnFKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="Int")]
		public System.Nullable<int> D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this.OnDChanging(value);
					this.SendPropertyChanging();
					this._D = value;
					this.SendPropertyChanged("D");
					this.OnDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_H", DbType="Int")]
		public System.Nullable<int> H
		{
			get
			{
				return this._H;
			}
			set
			{
				if ((this._H != value))
				{
					this.OnHChanging(value);
					this.SendPropertyChanging();
					this._H = value;
					this.SendPropertyChanged("H");
					this.OnHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L", DbType="Int")]
		public System.Nullable<int> L
		{
			get
			{
				return this._L;
			}
			set
			{
				if ((this._L != value))
				{
					this.OnLChanging(value);
					this.SendPropertyChanging();
					this._L = value;
					this.SendPropertyChanged("L");
					this.OnLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="VarChar(50)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CloseEndDay", DbType="VarChar(5)")]
		public string CloseEndDay
		{
			get
			{
				return this._CloseEndDay;
			}
			set
			{
				if ((this._CloseEndDay != value))
				{
					this.OnCloseEndDayChanging(value);
					this.SendPropertyChanging();
					this._CloseEndDay = value;
					this.SendPropertyChanged("CloseEndDay");
					this.OnCloseEndDayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
