<?xml version="1.0" encoding="utf-8"?><Database Name="AlsiDb" Class="WebDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=sql.alsitm.com,1444;Initial Catalog=AlsiDb;Persist Security Info=True;User ID=Pieter" SettingsObjectName="AlsiUtils.Properties.Settings" SettingsPropertyName="AlsiDbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="Pieter.TradeHistory" Member="TradeHistories">
    <Type Name="TradeHistory">
      <Column Name="n" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TimeStamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BuySell" Type="System.String" DbType="VarChar(4)" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Volume" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Trade_Profit" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Pieter.Settings" Member="Settings">
    <Type Name="Setting">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Setting_Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ValueString" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ValueNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Pieter.IndicatorSettings" Member="IndicatorSettings">
    <Type Name="IndicatorSetting">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="A1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="A2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="B1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="B2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="C1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="C2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="D1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="E1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="E2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="F1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="F2" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Pieter.EmailList" Member="EmailLists">
    <Type Name="EmailList">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="Pieter.TradeLog" Member="WebTradeLogs">
    <Type Name="WebTradeLog">
      <Column Name="N" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BuySell" Type="System.String" DbType="VarChar(4) NOT NULL" CanBeNull="false" />
      <Column Name="Reason" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Volume" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Column Name="ForeColor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BackColor" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PriceMatched" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Matched" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>