<?xml version="1.0" encoding="utf-8"?><Database Name="Sim" Class="SimDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PIETER-PC\SQLEXPRESS;Initial Catalog=Sim;Integrated Security=True" SettingsObjectName="NinjaTest.Properties.Settings" SettingsPropertyName="SimConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SS_RSI" Member="SS_RSIs">
    <Type Name="SS_RSI">
      <Column Name="C" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RSI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RSI_MA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RSI_MA2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mid_Long" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Mid_Short" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CloseLong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CloseShort" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Total_Profit" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Total_avg_PL" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Trade_Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PL_Ratio" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Avg_Profit" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Avg_Loss" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Pct_Profit" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Pct_Loss" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
</Database>